name: hourly-cron
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: POLL open predictions
        run: |
          curl --request POST \
          --url 'https://augur-predict.vercel.app/api/cron' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'
